### ISSUE TITLE
cooking.sh should error out if recipe not found

### ISSUE THREAD

**Issue by senior7515** [hakuch/CMakeCooking#10]
say you do `cooking.sh -r wellknown1234` but the recipe is `recipe/wellknown.cmake` cooking.sh will ignore not found recipe.

**Comment by hakuch** [comment]
I'm not able to reproduce this against `0.9.0`.

From `pantry/apple` (which has a recipe called "dev"):

```
$ ./cooking.sh -r devfoo
Cooking: The 'devfoo' recipe does not exist!
```

```
$ ./cooking.sh -r dev123
Cooking: The 'dev123' recipe does not exist!
```

```
$ ./cooking.sh -r foobar
Cooking: The 'foobar' recipe does not exist!
```

**Comment by senior7515** [comment]
i am using the one cooking.sh from seastar
