### ISSUE TITLE
Can't pass in additional buildsystem args to cooking.sh

### ISSUE THREAD

**Issue by nacl** [hakuch/CMakeCooking#24]
Hello!

As far as I can tell, there currently is no way consistent way to pass in args to the build generator.  This limits the generators that can be used effectively with it for a parallel build, which is essential for a speedy build process.

This doesn't impact builds with Ninja (the default), because it uses all available CPU cores.  However, it does somewhat prevent the use Makefiles without the use of [`MAKEFLAGS`](https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html) (I haven't tried it).

If this indeed works, it may be worth mentioning that in documentation.  Regardless, it would be nice if there was a standard way to pass in arguments to the initial `cmake --build` invocation that sets up all of the dependencies in advance of the initial project build.

**Comment by hakuch** [comment]
Thanks for the report. I agree that this would be useful.
