### ISSUE TITLE
the `project()` macro created `cmake/Cooking.cmake` changes its behavior

### ISSUE THREAD

**Issue by tchaikov** [hakuch/CMakeCooking#38]
we include seastar as a subproject using cmake. in addition to seastar, we are including other subprojects using cmake. but after preparing some seastar dependencies using `./cooking.sh`, i found that some variables which are supposed to be set by `project()`  are not set (correctly) anymore after `add_subdirectory(seastar)`.

for instance, without `cmake/Cooking.cmake`, `project()` of the subprojects included after seastar always set `PROJECT_NAME`, `PROJECT_SOURCE_DIR` and `<PROJECT-NAME>_SOURCE_DIR`. but with it, none of `PROJECT_NAME`, `PROJECT_SOURCE_DIR` and `<PROJECT-NAME>_SOURCE_DIR` is set correctly. if the subprojects in question rely on these cmake variables, cmake will fail to configure them.

in my case, we have a project with
```cmake
target_include_directories(dmclock PUBLIC
  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/src>
  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/support/src>)
```
so, after including  `cmake/Cooking.cmake` in seastar indirectly, the parent project won't be able to include the specified directories anymore.

the issue was originally filed against Seastar at https://github.com/scylladb/seastar/issues/645 .

**Comment by hakuch** [comment]
Thanks for the information!

There are two work-flows that Seastar supports with CMake:

- The first is to have a subdirectory in your repository which is the Seastar repository and to have the following line in your project's `CMakeLists.txt`: `add_subdirectory (my_seastar_dir)`.

- The second is to install Seastar somewhere and to use the CMake package mechanism to find the CMake targets (like `Seastar::seastar`, and `Seastar::seastar_testing`). With this work-flow, you would have a line like `find_package (Seastar REQUIRED)`.

cmake-cooking is only (presently) intended to work with the second work-flow. That is, if you would like to use cmake-cooking to supply the dependencies for your project which depends on Seastar, then you should not embed Seastar via `add_subdirectory`.

Would you please confirm that I've understood your report correctly, @tchaikov?

**Comment by tchaikov** [comment]
@hakuch if that's the case, we are using cmake-cooking in an unsupported way -- the first workflow.

thanks for you time. i am closing this issue.
