### ISSUE TITLE
how to enable a project for cmake ingredient

### ISSUE THREAD

**Issue by senior7515** [hakuch/CMakeCooking#6]
```
cooking_ingredient(smf
  COOKING_RECIPE wellknown
  COOKING_CMAKE_ARGS
    -DSMF_ENABLE_TESTS=OFF
    -DSMF_BUILD_PROGRAMS=OFF
  EXTERNAL_PROJECT_ARGS
    GIT_REPOSITORY https://github.com/smfrpc/smf.git
    GIT_TAG feature/cmakeconfig
    )

```

I think this is what is missing form smf to be able to be used by downstream projects 

https://github.com/smfrpc/smf/pull/305/commits/a5452d3ca4eae274723b29031ec3ca9bfaf89203

There is no example or `list` of requirements or something one can follow. 

I'm trying to consume smf on a downstream project and I am not sure how to debug it.

**Comment by senior7515** [comment]
@hakuch i think i managed to figure most of it out. now cooking.sh segfaults... whatever that means. 
![cmake_segfault](https://user-images.githubusercontent.com/175206/51012180-ee750680-1529-11e9-860e-660581c6d9b4.png)

**Comment by senior7515** [comment]
I guess this is more docs on how  to get cooking as an upstream ingredient to work by simply including it. 

What was required for smf was this:

```
if(SMF_INSTALL)
  include (GNUInstallDirs)
  include (CMakePackageConfigHelpers)
  set(install_cmakedir ${CMAKE_INSTALL_LIBDIR}/cmake/smf)
  install (
    DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/src/include/
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
  configure_package_config_file (
    ${CMAKE_CURRENT_LIST_DIR}/cmake/smf-config.cmake.in
    ${CMAKE_CURRENT_BINARY_DIR}/smf-config.cmake
    INSTALL_DESTINATION ${install_cmakedir})
  install (
    FILES
    ${CMAKE_CURRENT_BINARY_DIR}/smf-config.cmake
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindBoost.cmake
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/smf.cmake
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindZstd.cmake
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindxxHash.cmake
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindHdrhistogram.cmake
    DESTINATION ${install_cmakedir})
endif()

```

I had to look at the seastar cmake-foo to figure this out. 

So the docs should say - if you want your library to be consumed you need these cmake properties, etc.

**Comment by senior7515** [comment]
which also says that you need to have a smf-config.cmake file 

for which a default of smth like this seems to be doing the trick

```

@PACKAGE_INIT@
include(CMakeFindDependencyMacro)
find_dependency(smf)
include("${CMAKE_CURRENT_LIST_DIR}/@targets_export_name@.cmake")
check_required_components("@PROJECT_NAME@")
```

Basically someone using this methodology for cmake needs to know *what* is required to use it as a `consumer` and also as a `producer` of cooking_ingredients.

**Comment by hakuch** [comment]
The best reference for the CMake magic incantations is [this blog post](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/).

I'm closing this since it's not specific to cmake-cooking.
