### ISSUE TITLE
docs: how to debug when a recipe fails

### ISSUE THREAD

**Issue by senior7515** [hakuch/CMakeCooking#7]
Say you have a list of deps: 

all you get when a recipe fails is this: 
```
ninja: build stopped: subcommand failed.
```

How does one go about debugging the build? 

It is not entirely clear to me how to go about fixing one issue or another.

**Comment by hakuch** [comment]
This is a question and not an issue description. I will close this issue and re-open another one which addresses the actual problem, which looks to be one of missing documentation.

To answer your question (and to provide the basis of the documentation that we'll add), the Ninja generator runs concurrent jobs by default.

As a result, when a single ingredient fails, all the other jobs (there will be `N` if your system has `N` threads) will continue to execute for some time until Ninja synchronizes (I'm not sure of the particulars of how Ninja actually works in this respect).

Additionally, Ninja does output buffering so the error can be hard to spot if you're looking for it interactively.

Therefore, the best way to find the error is to scroll up in your terminal buffer to locate the actual error.

There can be a lot of stuff to scroll through, so an alternative solution is to instead use the `Unix Makefiles` generator which runs a single job by default:

```
./cooking.sh -r my_recipe -g 'Unix Makefiles'
```

This will execute one ingredient at a time and with no buffering. It should make identifying the error much easier.
