### ISSUE TITLE
docs: feature request: Explain dependency re-declaration

### ISSUE THREAD

**Issue by senior7515** [hakuch/CMakeCooking#9]
There is no mailing list, so we can use this for now until it picks up - also serves for docs when ppl google things.

so on smf we have to re-declare FindBoost.cmake because we *depend* on boost. However, I know that my boost usage is a subset of seastar boost. 

It's not entirely clear to me when you have to re-declare the cooking_ingredients in child recipes. 

For example, for my SMF projects, my consumers are happy to take the deps at the versions I list. 

If they too depend on say Flatbuffers headers why should they re-declare the dependency. 

I'm not sure I understand when and why one has to re-declare by *copy/pasting* upstream ingredients into one's recipe. 

Is there a first class citizen that says - also include upstream ingredient as my own - in full. 

maybe an annotation on the cooking_ingredient function like this. 

```
cooking_ingredient(SMF
   USE_ALL_DEPS_HEADERS_TOO # well a better name but you get the gist
```
Or maybe a way to say, take all use these upstream deps as is. like this

```
cooking_ingredient(smf
    USE_FULL_DEPS
        Flatbuffers
        Seastar
        Boost
.....
```

Because redeclaring is tedius and error prone. 

Thoughts?

**Comment by hakuch** [comment]
It's not necessary to re-declare recipes for direct dependencies.

If you wished, you could omit declaring your own `Boost` recipe and use the one provided by a dependency. This should still work.

However, the reason that I recommend providing recipes for all of your direct dependencies is control.

For example, suppose that a project only used the `unit_test_framework` library from Boost and in their recipe for Boost, they include only that library when Boost is compiled. Furthermore, suppose that project compiles Boost in "release" mode and we want a debugging version.

In that case, if we provide our own recipe for Boost, then we can just override our dependency's version with the configuration of Boost that we would like.

**Comment by hakuch** [comment]
Consider another scenario.

Suppose I depend on `smf`, which depends on `Boost`. I also depend on `magic` (I just made it up) that *also* depends on Boost.

If I don't declare my own Boost recipe, I *could* say "`magic` depends on `smf`" to ensure that first `smf` is compiled (along with the internal Boost ingredient) and then only after `magic` is.

However, that wouldn't accurately or clearly reflect the reality of the situation.

Instead, we can actually say "here is the recipe for Boost exactly how my project needs it", and "`smf` depends on `Boost`" and "`magic` depends on `Boost`".

If a project depended on *us* and wanted to provide their own copy of `magic`, then our recipe would enforce dependencies in the build that didn't need to exist.

**Comment by hakuch** [comment]
One of the principals that I've developed while thinking about this tool is that each project ought to know its exact requirements in isolation of its dependencies' own requirements.

You can sort of stretch this into thinking about mathematical functions and functional composition.

You can imagine a function `F(A, B, C)` where `A`, `B`, and `C` are my dependencies at fixed versions and configurations.

It may be that `B` itself is a function `B(C)` (with shared dependency on `C`).

The solution is therefore to compose `F` and `B` into a new function:

```
G(A, B, C) = F(A, B(C), C)
```

**Comment by senior7515** [comment]
On Mon, Jan 14, 2019 at 4:42 PM Jesse Haber-Kucharsky <
notifications@github.com> wrote:

> One of the principals that I've developed while thinking about this tool
> is that each project ought to know its exact requirements in isolation of
> its dependencies' own requirements.
>
> You can sort of stretch this into thinking about mathematical functions
> and functional composition.
>
> You can imagine a function F(A, B, C) where A, B, and C are my
> dependencies at fixed versions and configurations.
>
> It may be that B itself is a function B(C) (with shared dependency on C).
>
> The solution is therefore to compose F and B into a new function:
>
> G(A, B, C) = F(A, B(C), C)
>
>
I agree in principle.

In practice to do this, you need the transitive closure of definitions in
one file to build. Think of builds that do not have access to the internet
for example.

In that world what you would do is you copy-paste the definitions into the
sum (where the sum type is concatenation /merge of recipes).

Downstream projects only understand their immediate deps. So to them, and
for compatibility (see the note on the boost 1.64 vs 1.67 for seastar for
example) often times you explicitly do not re-define your deps.
because to you compatibility w/ libs is a key driver.

But i tested this and it works as expected. so no issue here, just seems
worth explaining that you can *choose* to do either. In the docs it seems
as though you only have one option where this is not true when you try it.

So take this as an experience report. Feel free to close :)

**Comment by hakuch** [comment]
We'll try to improve the documentation over time. Thanks for the feedback!

**Comment by senior7515** [comment]
I think maybe re-opening and closing when the docs get in would be my suggested approach. I'm happy to give you feedback on the docs/PR. 

Otherwise I wouldn't know if it addresses the comments tho. Up to you.
